// Generated by CoffeeScript 1.3.3
(function() {
  var console,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  console = window.console;

  (function(window) {
    var g;
    g = function(el, parameters) {
      var $, attr, val;
      $ = el;
      if (typeof $ === "string") {
        if (!!$.match(/(<\/?[^>]+>)/gi)) {
          $ = document.createElement(el.replace(/[^a-zA-Z]/gi, ""));
        } else {
          $ = document.getElementsByTagName(el);
        }
      }
      if (parameters != null) {
        for (attr in parameters) {
          val = parameters[attr];
          el[attr] = val;
        }
      }
      __extends($, g.prototype);
      return $;
    };
    g.prototype = {
      addClass: function(c) {
        console.log(this, c);
        return this;
      }
    };
    g.fn = g.prototype;
    return window.g = g;
  })(window);

}).call(this);
