// Generated by CoffeeScript 1.3.3
(function() {
  var console;

  console = window.console;

  (function(window, doc, g) {
    var Gridsee, events, ns;
    ns = "gridsee";
    events = {
      click: "click." + ns
    };
    Gridsee = (function() {

      function Gridsee() {
        this.model();
        this.view();
        this.controller();
      }

      Gridsee.prototype.model = function() {};

      Gridsee.prototype.view = function() {
        return this.$ = {
          body: g(doc.body),
          pageEls: g("<div />", {
            id: "" + ns + "-wrapper"
          }),
          fakebody: g("<body />"),
          canvas: g("<canvas />"),
          settings: g("<div />"),
          menu: g("<button />")
        };
      };

      Gridsee.prototype.controller = function() {
        var Popup, popup,
          _this = this;
        Popup = (function() {

          function Popup(x) {
            this.isOpen = false;
          }

          Popup.prototype.open = function() {
            this.isOpen = true;
            return console.log("open");
          };

          Popup.prototype.close = function() {
            this.isOpen = false;
            return console.log("close");
          };

          Popup.prototype.toggle = function() {
            return this[this.isOpen ? "close" : "open"]();
          };

          return Popup;

        })();
        popup = new Popup();
        (function() {
          _this.$.menu.on(events.click, function(e) {
            return popup.toggle();
          }).appendTo(_this.$.body);
          return console.log(_this.$.pageEls);
        })();
      };

      return Gridsee;

    })();
    return window.Gridsee = new Gridsee();
  })(window, document, jQuery);

}).call(this);
