// Generated by CoffeeScript 1.3.3
(function() {
  var console;

  console = window.console;

  (function(window, doc, g) {
    var Gridsee;
    Gridsee = (function() {

      function Gridsee() {
        this.model();
        this.view();
        this.controller();
      }

      Gridsee.prototype.model = function() {};

      Gridsee.prototype.view = function() {
        return this.$ = {
          body: g(doc.body),
          pageEls: g("<div />", {
            id: "y"
          }),
          fakebody: g("<body />"),
          canvas: g("<canvas />"),
          settings: g("<div />"),
          menu: g("<div />")
        };
      };

      Gridsee.prototype.controller = function() {
        var _this = this;
        return (function() {
          return console.log(_this.$.pageEls);
        })();
      };

      return Gridsee;

    })();
    return window.Gridsee = new Gridsee();
  })(window, document, jQuery);

}).call(this);
