// Generated by CoffeeScript 1.3.3

/* --------------------------------------------
     Begin constructor.coffee
--------------------------------------------
*/


(function() {
  var View, console;

  window.Gridsee = (function() {

    function Gridsee() {}

    return Gridsee;

  })();

  /* --------------------------------------------
       Begin model.coffee
  --------------------------------------------
  */


  console = window.console;

  console.log("model");

  /* --------------------------------------------
       Begin view.coffee
  --------------------------------------------
  */


  View = (function() {

    function View() {
      this.$ = {
        canvas: document.createElement("canvas")
      };
    }

    return View;

  })();

  /* --------------------------------------------
       Begin controller.coffee
  --------------------------------------------
  */


  console.log("controller");

}).call(this);
